# 코드 10-3 빌드 실행

script:
  - sh travis_scripts/tag_build.sh
  - sh travis_scripts/build_services.sh
  - sh travis_scripts/deploy_to_docker_hub.sh
  - sh travis_scripts/deploy_to_amazon_ecs.sh
  - sh travis_scripts/trigger_platform_tests.sh
